// Renders the three financial statements as a single, well-designed PDF —
// client-side only (react-pdf), since Fabrica has no backend server.
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { marginBottom: 18, borderBottom: "2pt solid #1a1a1a", paddingBottom: 10 },
  brand: { fontSize: 16, fontWeight: 700, marginBottom: 2 },
  tagline: { fontSize: 9, color: "#666666", marginBottom: 8 },
  statementTitle: { fontSize: 13, fontWeight: 700, marginTop: 4 },
  statementSub: { fontSize: 9, color: "#666666", marginTop: 2 },
  sectionLabel: { fontSize: 9, fontWeight: 700, color: "#666666", textTransform: "uppercase", marginTop: 14, marginBottom: 4, letterSpacing: 0.5 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  rowIndent: { paddingLeft: 14 },
  rowDivider: { borderTop: "0.5pt solid #cccccc", marginTop: 3, paddingTop: 5 },
  rowStrong: { fontWeight: 700 },
  rowLarge: { fontSize: 12 },
  label: { flexGrow: 1 },
  value: { textAlign: "right", minWidth: 90 },
  muted: { color: "#888888", fontSize: 8 },
  columns: { flexDirection: "row", gap: 24, marginTop: 4 },
  column: { flex: 1 },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#999999", textAlign: "center", borderTop: "0.5pt solid #eeeeee", paddingTop: 6 },
  notice: { fontSize: 8.5, color: "#555555", backgroundColor: "#f5f5f5", padding: 8, marginTop: 14, lineHeight: 1.4 },
});

function Row({ label, value, strong, indent, divider, large, muted }) {
  return (
    <View style={[styles.row, indent && styles.rowIndent, divider && styles.rowDivider, strong && styles.rowStrong, large && styles.rowLarge]}>
      <Text style={[styles.label, muted && styles.muted]}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

function Header({ branding, title, sub }) {
  return (
    <View style={styles.header}>
      <Text style={styles.brand}>{branding?.name || "Fabrica"}</Text>
      {branding?.tagline ? <Text style={styles.tagline}>{branding.tagline}</Text> : null}
      <Text style={styles.statementTitle}>{title}</Text>
      <Text style={styles.statementSub}>{sub}</Text>
    </View>
  );
}

function Footer({ generatedAt }) {
  return (
    <Text style={styles.footer}>
      Generated by Fabrica on {generatedAt} · Figures in {"local currency"} · Unaudited, for internal management use
    </Text>
  );
}

export function FinancialStatementsDocument({ branding, money, income, balance, cashFlow, generatedAt }) {
  const opex = income.operatingExpenses;
  return (
    <Document title={`${branding?.name || "Fabrica"} — Financial Statements`}>
      <Page size="A4" style={styles.page}>
        <Header branding={branding} title="Income Statement" sub={`${income.period.from || "Inception"} to ${income.period.to}`} />

        <Row label="Revenue" value={money(income.revenue)} strong />
        <Row label="Cost of goods sold" value={`(${money(income.cogs)})`} indent />
        <Row label="Gross profit" value={money(income.grossProfit)} strong divider />
        <Row label="Gross margin" value={`${income.grossMarginPct}%`} muted />

        <Text style={styles.sectionLabel}>Operating expenses</Text>
        {opex.byCategory.map((c) => <Row key={c.category} label={c.category} value={`(${money(c.amount)})`} indent />)}
        <Row label="Marketing / CSR — product giveaways" value={`(${money(opex.giveawayValue)})`} indent />
        <Row label="Production loss" value={`(${money(opex.productionLossValue)})`} indent />
        <Row label="Spoilage" value={`(${money(opex.spoilageValue)})`} indent />
        <Row label="Depreciation" value={`(${money(opex.depreciationTotal)})`} indent />
        <Row label="Total operating expenses" value={`(${money(opex.total_all)})`} strong divider />

        <Row label="Net income" value={money(income.netIncome)} strong large divider />

        <Footer generatedAt={generatedAt} />
      </Page>

      <Page size="A4" style={styles.page}>
        <Header branding={branding} title="Balance Sheet" sub={`As of ${balance.asOf}`} />

        <View style={styles.columns}>
          <View style={styles.column}>
            <Text style={styles.sectionLabel}>Assets</Text>
            <Row label="Cash & Bank" value={money(balance.assets.cashAndBank)} />
            <Row label="Accounts receivable" value={money(balance.assets.accountsReceivable)} />
            <Row label="Inventory — raw materials" value={money(balance.assets.inventoryRawMaterials)} />
            <Row label="Inventory — finished goods" value={money(balance.assets.inventoryFinishedGoods)} />
            <Row label="Fixed assets, at cost" value={money(balance.assets.fixedAssetsCost)} />
            <Row label="Accumulated depreciation" value={`(${money(balance.assets.accumulatedDepreciation)})`} indent />
            <Row label="Total assets" value={money(balance.assets.total)} strong divider />
          </View>
          <View style={styles.column}>
            <Text style={styles.sectionLabel}>Liabilities</Text>
            <Row label="Accounts payable" value={money(balance.liabilities.accountsPayable)} />
            <Row label="VAT payable" value={money(balance.liabilities.vatPayable)} />
            <Row label="Accrued expenses" value={money(balance.liabilities.accruedExpenses)} />
            <Row label="Total liabilities" value={money(balance.liabilities.total)} strong divider />

            <Text style={styles.sectionLabel}>Equity</Text>
            <Row label="Owner's capital" value={money(balance.equity.ownersCapital)} />
            <Row label="Owner's drawings" value={`(${money(balance.equity.ownersDrawings)})`} indent />
            <Row label="Retained earnings" value={money(balance.equity.retainedEarnings)} />
            <Row label="Total equity" value={money(balance.equity.total)} strong divider />
          </View>
        </View>

        <Text style={styles.notice}>
          {balance.balances
            ? "Assets = Liabilities + Equity — this sheet balances."
            : "This sheet does not balance — please review the underlying data."}
          {"  "}Cash & Bank, VAT/accrued liabilities, and Owner's Equity are tracked from the day the
          Financials module went live, not backfilled; Revenue, receivables, payables, and inventory
          value reflect full history. Retained Earnings absorbs the difference so the sheet balances.
        </Text>

        <Footer generatedAt={generatedAt} />
      </Page>

      <Page size="A4" style={styles.page}>
        <Header branding={branding} title="Cash Flow Statement" sub={`${cashFlow.period.from || "Inception"} to ${cashFlow.period.to} · direct method`} />

        <Row label="Opening cash & bank" value={money(cashFlow.openingCash)} />
        <Text style={styles.sectionLabel}>Cash flow</Text>
        <Row label="Operating activities" value={money(cashFlow.operating.total)} indent />
        <Row label="Investing activities" value={money(cashFlow.investing.total)} indent />
        <Row label="Financing activities" value={money(cashFlow.financing.total)} indent />
        <Row label="Net change in cash" value={money(cashFlow.netChange)} strong divider />
        <Row label="Closing cash & bank" value={money(cashFlow.closingCash)} strong large divider />

        <Text style={styles.notice}>
          {cashFlow.reconciles
            ? "Opening cash plus net change equals closing cash."
            : "Opening cash plus net change does not equal closing cash — please review the underlying data."}
          {"  "}Reflects only cash movement recorded in the ledger since the Financials module went
          live — it does not reconstruct cash activity from before then.
        </Text>

        <Footer generatedAt={generatedAt} />
      </Page>
    </Document>
  );
}

export async function downloadFinancialStatementsPdf({ branding, money, income, balance, cashFlow, fileName }) {
  const generatedAt = new Date().toLocaleString();
  const doc = (
    <FinancialStatementsDocument branding={branding} money={money} income={income} balance={balance} cashFlow={cashFlow} generatedAt={generatedAt} />
  );
  const blob = await pdf(doc).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName || "financial-statements.pdf";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
